
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lzlz000/tiny-service-config-repo.git
  rabbitmq:
    host: lzlz.site
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


management:
  endpoints:
    web:
      expose: "*"
server:
  port: 38001
